# Generated by Django 5.2.4 on 2026-04-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_business_product_business_sale_business_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='last_trial_reminder_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='subscription_plan',
            field=models.CharField(choices=[('trial', 'Trial'), ('starter_5000', 'Starter - N5,000'), ('growth_10000', 'Growth - N10,000'), ('pro_20000', 'Pro - N20,000')], default='trial', max_length=20),
        ),
        migrations.AddField(
            model_name='business',
            name='trial_ends_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='trial_started_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
